configuration:
    # Checks for gibberish in the user's answer. For example:
    # 
    # njdasndisasidasadii -> Will not pass
    # I like monkeys -> Will pass
    #
    # By default it uses a pre-trained english matrix. If you want to enable this feature in another language, you will need to train the bot yourself!
    gibberish_detection: true

buttons:
    start_button: |
        üìù - Apply
    developer_button: |
        üßë‚Äçüíª - Developer
    cancel: |
        ‚ùå - Cancel
    home: |
        üè† - Return to the home
    start_work: |
        ‚úÖ - I'm sure
    source_button: |
        üìé - Source code
    fetch_model: |
        ‚¨á - Get current model
    train_model: |
        ‚¨Ü - Train new model

types:
    moderator:
        name: |
            Moderator
        description: |
            The moderator is an important figure for the group, responsible for monitoring the group and resolving any issues that may arise.
        questions:
            1:
                name: |
                    ¬ª Why do you want to be part of our staff?
                type: text
                min_length: 10
                max_length: 1000
            2:
                name: |
                    ¬ª How old are you?
                type: number
                min_length: -1
                max_length: -1
            3:
                name: |
                    ¬ª Do you like monkeys? Why?
                type: text
                min_length: 0
                max_length: 10000
    writer:
        name: |
            Writer
        description: |
            You write stuff
        questions: []
    developer:
        name: |
            Developer
        description: |
            You code stuff and smash your head onto the keyboard.
        questions: []
messages:
    start: |
        <b>Welcome to the Staff Application Bot!</b>

        Please choose an option:

        ‚Ä¢ <b>Apply:</b> Start your staff application.
        ‚Ä¢ <b>Developer:</b> Contact us for bot-related questions or feedback.
        ‚Ä¢ <b>Source Code:</b> View the source code for this bot.

        If you have any questions or concerns, please let us know.
    chooser: |
        <b>Please select the application you want to complete:</b>

        Click on the "‚Ñπ" button next to an application to get more information.

        Please select only one application to complete. Thank you!
    disclaimer: |
        <b>Disclaimer:</b> We take staff applications seriously. Any troll or meme applications will result in a permanent ban from this bot. Please only submit a staff application if you are serious about joining our team.

        If you are ready to begin your application, click the button below. If you are unsure or want to return to the home screen, click the "Return to Home" button.

        Good luck with your application!
    question_template: |
        üìë | <b>Question no.{number}</b>
        {message}
        ‚ùå ‚Äì If you want to cancel your application, click the button below.
    work_done: |
        <b>Thank you for completing your staff application!</b>

        We appreciate the time and effort you put into answering our questions.

        Please understand that we receive many applications and cannot accept everyone, but we appreciate your interest in joining our team. We wish you the best of luck with your future endeavors.

        Thank you again for your application!
    new_application: |
        <b>New Staff Application!</b>

        A new staff application has been submitted by <a href="tg://user?id={userId}">{userName}</a> [<code>{userId}</code>]. 
        Application Type: {type}
        
        Please click the link below to view the answers:
        <a href="{link}">Click here to view answers</a>
    accepted: |
        <b>Congratulations!</b>

        We are pleased to inform you that your staff application has been accepted! You have been invited to join our staff Telegram group, where you will receive further instructions and get to know our team members.

        Please join the group using the link below:

        <a href="{link}">Join Our Staff Group</a>

        Thank you for your interest in joining our team, and we look forward to working with you!
    sending_answers: |
        ‚è≥ <b>Sending answers...</b>
    already_in_progress: |
        You are already doing a staff application!
    already_sent: |
        You already did a staff application before!
    work_cancelled: |
        You have cancelled your application.
    not_in_progress: |
        You are in no staff application at the moment!
    answer_not_valid: |
        Sorry, but the answer is not valid. This question accepts only '{type}' answers
    invalid_length: |
        Sorry, this answer does not meet the current question criteria. Your answer needs to be at least {min} characters long and {max} maximum. Your answer has {length} characters
    only_numbers_answer: |
        <b>This question requires a number!</b>
    gibberish_detected: |
        Please do not use gibberish in your answers.
    work_with_no_question: |
        This type of application has no questions to answer. Please come back later.
    error_while_working: |
        There was an error while sending your answers to the admins. Please try again later.
    banned: |
        You are banned. You can't use this bot.
    
    # Admin messages
    invalid_usage: |
        Please provide a valid user id to {use}. Correct usage: <code>{command} [user id]</code>
    invalid_id: |
        Please provide a valid user id. Correct usage: <code>{command} [user id]</code>
    user_not_registered: |
        User is not registered.
    user_already_accepted: |
        User is already accepted.
    user_accept_banned: |
        User is banned. You can't accept them.
    user_accept_no_questions: |
        User has not answered any questions yet.
    user_accepted: |
        User accepted successfully.
    user_unban_not_banned: |
        User is not banned.
    user_unbanned: |
        User unbanned successfully.
    user_ban_already_banned: |
        User is already banned.
    user_banned: |
        User banned successfully.
    
    # Training messages
    train_menu: |
        <b>Welcome to the train menu!</b>

        1. Fetch Current Training Data: This option will allow you to retrieve the current training data in a JSON file format. You can use this data to examine the current state of the bot's knowledge and make any necessary changes.

        2. Train Bot: This option will start the training process for the bot, allowing it to improve its language and conversation skills based on new data.

        Please select the option you would like to proceed with.
    training_first_phase: |
        üëã To commence our training process, I require three files.

        ‚Ä¢ Firstly, I need a substantial collection of diverse and legitimate words. It's preferable that the file is at least a few megabytes in size. However, please avoid selecting literature from science fiction and fantasy genres, as these often contain uncommon word formations. (ü§î For instance, the default model was trained using a Sherlock Holmes novel.) <a href="https://raw.githubusercontent.com/ImOnlyFire/applications-bot/main/gibberish/defaults/good.txt">Example</a>

        ‚Ä¢ Secondly, I need a file with around 20 simple and straightforward phrases that are easy to comprehend and free of complex language or unusual word formations. <a href="https://raw.githubusercontent.com/ImOnlyFire/applications-bot/main/gibberish/defaults/goodsm.txt">Example</a>

        ‚Ä¢ Finally, I need a file filled with overtly bad words and gibberish. This file will assist our AI model in learning what constitutes gibberish text and how to recognize it. üßê <a href="https://raw.githubusercontent.com/ImOnlyFire/applications-bot/main/gibberish/defaults/bad.txt">Example</a>
       
        <b>Let's start with the first file. Just send me the text file containing the stuff I said in the first bullet point.</b>
    training_second_phase: |
        Seems good! Now please send the second file. 
    training_final_phase: |
        Good job! now please send the last file.
    training_in_progress: |
        ‚è≥ <b>Training...</b>
    training_done: |
        üéâ Training process has been completed!
    training_cancelled: |
        Training process has been cancelled.
