buttons:
    start_button: |
        ğŸ“ - INIZIA la tua candidatura
    developer_button: |
        ğŸ§‘â€ğŸ’» - Sviluppatore
    cancel: |
        âŒ - ANNULLA
    home: |
        ğŸ  - Torna alla HOME
    start_work: |
        âœ… - Sono SICURO
    source_button: |
        ğŸ“ - Codice Sorgente

types:
    moderator:
        name: |
            ğŸŒŸ â€“ MODERATORE
        description: |
            Il moderatore Ã¨ una figura importante per il gruppo, Ã¨ colui che si occupa di controllare il gruppo e di risolvere eventuali problemi che si possono verificare.
        questions:
            # if required is false, the bot will say that the answer is optional and there will be a button to skip it
            1:
                name: |
                    Â» <b>PerchÃ©</b> vuoi candidarti per il ruolo di <b>MODERATORE</b>?
                type: text
                # required: true
                min_length: 10
                max_length: 1000
            2:
                name: |
                    Â» quanti anni hai
                type: number
                # required: true
                min_length: 0
                max_length: 0 
    writer:
        name: |
            ğŸ“š â€“ SCRITTORE
        description: |
            Lo scrittore e' utile.
        questions: []
messages:
    start: |
        ğŸ—³| <b>CANDIDATURE MINECRAFT-TG24</b>
        Â» Benvenuto nel <b>BOT</b> di MinecraftTG24 in cui potrai svolgere la tua candidatura per diventare <b>MODERATORE</b> del <b>GRUPPO</b>.

        ğŸ¤– â€“ Il nostro <b>BOT</b> ti guiderÃ  nello svolgimento della candidatura, ponendoti diverse domande che ci aiuteranno a capire le tue <b>MOTIVAZIONI</b> e le tue <b>ABILITA'</b> per diventare un moderatore.
    chooser: |
        ğŸ§Š| <b>SCELTA DELLA CANDIDATURA</b>

        Qui potrai scegliere il ruolo per il quale vuoi candidarti. Ricorda che puoi candidarti per un solo ruolo alla volta!

        Se vuoi avere piÃ¹ informazioni su un determinato ruolo, clicca sul pulsante â„¹ che si trova accanto ad ogni ruolo!
    disclaimer: |
        ğŸ’¡| <b>IMPORTANTE</b>
        Â» Prima di iniziare la candidatura, ti consigliamo di leggere attentamente IL <b>REGOLAMENTO</b> del gruppo al seguente link: (https://t.me/MTG24Chat/822694).

        Â» Avrai a disposizione <b>7 MINUTI</b> per rispondere alle domande, quindi prenditi il tempo necessario per fornire la risposta piÃ¹ adeguata. Ricorda che una volta inviata la risposta, non sarÃ  possibile modificarla!

        ğŸ‘‰| Per procedere con la <b>CANDIDATURA</b>, clicca sul pulsante sottostante.

        ğŸ | Tieni presente che le candidature in forma di <b>TROLL</b> o <b>MEME</b> saranno punite con un <b>BAN PERMANENTE</b> dal bot e un <b>BAN TEMPORANEO</b> dal gruppo.
    only_numbers_answer: |
        <b>Questa domanda richiede un numero</b>
    question_template: |
        ğŸ“‘ | <b>DOMANDA N. {number}</b>
        {message}
        âŒ â€“  Se desideri <b>ANNULLARE</b> il tuo provino, clicca il <b>BOTTONE</b> qui sotto.
    work_done: |
        âœ… <b>Grazie per aver completato la candidatura!</b>
        <i>Se verrai accettato, te lo faremo sapere tramite questo bot.</i>

        <b>â€” Purtroppo non possiamo accettare tutti, ma non ti preoccupare, ci saranno altre opportunitÃ  in futuro</b>
    new_application: |
        ğŸ§¾ <b>NUOVO PROVINO!</b>

        ğŸš¹â€¢ <b>Utente</b>: <a href="tg://user?id=%s">%s</a> [<code>%s</code>]

        â“â€¢ <b>RISPOSTE</b>
        %s

        â€” <b>APRI IL LINK PER VEDERE LE RISPOSTE!</b>
    accepted: |
        âœ… | <b>STATO CANDIDATURA </b>

        <i>Â»</i> Complimenti! La tua <b>CANDIDATURA</b> Ã¨ stata <b>ACCETTATA</b> dallo staff. Ho creato un link temporaneo per entrare 
        nella nostra <b>CHAT</b>.

        â€“ <a href="%s">Clicca qui</a> per entrare

        â›”ï¸ â€“ <b>ATTENZIONE</b>
        <i>Â»</i> <b>PUBBLICARE</b> o <b>CONDIVIDERE</b> il <b>LINK DI INVITO</b> Ã¨ severamente <b>VIETATO</b> e farlo comporterÃ  una sanzione 
        all'interno del nostro gruppo pubblico.
    already_in_progress: |
        Sei gia' in un provino!
    already_sent: |
        Hai gia' inviato un provino precedentemente!
    work_cancelled: |
        Hai annullato la candidatura.
    not_in_progress: |
        Non sei in nessuna candidatura!
    answer_not_valid: |
        Risposta non valida. Questa domanda accetta solo risposte di tipo {type}
    invalid_length: |
        La risposta non Ã¨ valida. Questa domanda deve essere lunga almeno {min} caratteri e al massimo {max} caratteri. La tua risposta ha {length} caratteri.
