configuration:
    # Checks for gibberish in the user's answer. For example:
    # 
    # njdasndisasidasadii -> Will not pass
    # I like monkeys -> Will pass
    #
    # By default it uses a pre-trained english matrix. If you want to enable this feature in another language, you will need to train the bot yourself!
    gibberish_detection: true

buttons:
    start_button: |
        ğŸ“ - Candidati
    developer_button: |
        ğŸ§‘â€ğŸ’» - Developer
    cancel: |
        âŒ - Cancella
    home: |
        ğŸ  - Torna alla home
    start_work: |
        âœ… - Sono sicuro
    source_button: |
        ğŸ“ - Source code
    fetch_model: |
        â¬‡ - Get current model
    train_model: |
        â¬† - Train new model

types:
    researcher:
        name: |
            Info Researcher
        description: |
            The moderator is an important figure for the group, responsible for monitoring the group and resolving any issues that may arise.
        questions:
            # if required is false, the bot will say that the answer is optional and there will be a button to skip it
            # Currently does not work
            1:
                name: |
                    Â» Why do you want to be part of our staff?
                type: text
                # required: true
                min_length: 10
                max_length: 1000
            2:
                name: |
                    Â» How old are you?
                type: number
                # required: true
                min_length: -1
                max_length: -1
            3:
                name: |
                    <i>Â»</i> PerchÃ© dovremmo <b>SCEGLIERE</b> proprio <b>TE</b>? Cosa ti rende un candidato <b>MIGLIORE</b> rispetto agli altri? Questa domanda ci aiuterÃ  a capire perchÃ© dovremmo sceglierti rispetto agli altri candidati.
                type: text
                required: true
                min_length: 0
                max_length: 10000
    writer:
        name: |
            Writer
        description: |
            You write stuff
        questions:
            # if required is false, the bot will say that the answer is optional and there will be a button to skip it
            # Currently does not 
            1:
                name: |
                    <i>Â»</i> <b>ETA</b>': Quanti <b>ANNI</b> hai? Questa informazione ci aiuterÃ  a conoscere meglio il candidato.
                type: number
                required: true
                min_length: 10
                max_length: 1000
            2:
                name: |
                    <i>Â» </i>Quali sono le <b>motivazioni</b> che ti spingono a candidarti come <b>SCRITTORE</b> del <b>canale</b>?
                    Vogliamo capire quali sono i tuoi obiettivi e motivazioni per entrare a far parte del team.
                type: text
                required: true
                min_length: 10
                max_length: 1000
            3:
                name: |
                    <i>Â»</i> Quali sono le tue esperienze passate come <b>SCRITTORE</b>? Se non ne possiedi, procedi scrivendo <b>"nessuna"</b>.
                type: text
                required: true
                min_length: 0
                max_length: 10000
            4:
                name: |
                    <i>Â»</i> Hai una specializzazione o un <b>interesse particolare in un determinato argomento</b>? o settore tematico?
                    Alcuni dei settori che trattiamo sono: <i>News, Esclusive, Minecraft Live, Interviste e CuriositÃ </i>.
                type: text
                required: true
                min_length: 0
                max_length: 10000
            5:
                name: |
                    <i>Â»</i> Come gestisci il <b>feedback e le critiche</b> sui tuoi scritti? Sei aperto a <b>ricevere suggerimenti e apportare modifiche</b>?
                type: text
                required: true
                min_length: 0
                max_length: 10000
            6:
                name: |
                    <i>Â»</i> Come lavori in <b>team</b>? Hai <b>esperienze precedenti di collaborazione</b> con altri scrittori?
                type: text
                required: true
                min_length: 0
                max_length: 10000
            7:
                name: |
                    <i>Â»</i> Come ti senti nel <b>rispettare scadenze</b> e lavorare su <b>progetti con limiti di tempo</b> definiti?
                type: text
                required: true
                min_length: 0
                max_length: 10000
            8:
                name: |
                    <i>Â»</i> Come ti <b>organizzi nel processo di scrittura</b>? Hai uno <b>schema o una routine</b> specifica che segui?
                type: text
                required: true
                min_length: 0
                max_length: 10000
            9:
                name: |
                    <i>Â»</i> Potresti <b>condividere uno o piÃ¹ esempi di post o articoli che hai scritto in passato</b>?
                    Sarebbe fantastico avere <b>un'idea piÃ¹ concreta</b> del tuo <b>stile di scrittura</b>.
                type: text
                required: true
                min_length: 0
                max_length: 10000
            10:
                name: |
                    <i>Â»</i> PerchÃ© dovremmo <b>scegliere</b> proprio <b>te</b>? Cosa ti rende un candidato <b>MIGLIORE</b> rispetto agli altri?
                    Questa domanda ci aiuterÃ  a capire perchÃ© dovremmo sceglierti rispetto agli altri candidati.
                type: text
                required: true
                min_length: 0
                max_length: 10000
    developer:
        name: |
            Developer
        description: |
            You code stuff and smash your head onto the keyboard.
        questions: []
messages:
    start: |
        ğŸ’¼ â€¢ <b>SEI PRONTO PER LA TUA CANDIDATURA?</b>
        <i>Â»</i> Benvenuto nella <i>sezione candidature</i> di <b>Minecraft TG24</b>.
        Utilizza i pulsanti per <b>muoverti tra le nostre sezioni</b>.

        (â—ï¸) â€” <b>PER PROCEDERE CON LA CANDIDATURA, UTILIZZA IL TASTO "ğŸ“ - Candidati"!</b>
    chooser: |
        ğŸ’¼ â€¢ <b>SEI PRONTO PER LA TUA CANDIDATURA?</b>
        <i>Â»</i> Scegli uno tra i <b>ruoli</b> che vorresti ricoprire!
        Se desideri <b>maggiori informazioni</b>, utilizza il pulsante "â„¹"!
    disclaimer: |
        ğŸ”´ â€¢ <b>DISCLAIMER, SEI PREGATO DI LEGGERE ATTENTAMENTE!</b>
        <i>Â»</i> Prendiamo <b>molto seriamente</b> le candidature staff. Sei pregato di <b>non inviare candidature meme o troll</b>, in caso contrario saremo pronti a <b>prendere provvedimenti</b>.

        ğŸ¥‡ â€“ <b>COME PROCEDERE!</b>
        <i>Â»</i> Nel caso tu sia pronto, utilizza il pulsante sottostante per procedere alla candidatura. 

    question_template: |
        ğŸ“‘ â€¢ <b> Domanda numero.{number}</b>
        {message}
        <b>(âŒ) â€“ Se vuoi cancellare la tua candidatura, clicca il pulsante.</b>
    work_done: |
        <b>ğŸ† â€¢  GRAZIE PER AVER COMPLETATO LA TUA CANDIDATURA!</b>
        <i>Â»</i> Apprezziamo il <b>tempo e l'impegno</b> impiegato per rispondere alle nostre domande.

        <b>âš¡ï¸ â€“ LE TUE RISPOSTE VERRANO VISIONATE</b>
        <i>Â»</i> La tua candidatura verrÃ  <b>presa sotto carico a breve</b>. Nel caso in cui dovessi <b>essere accettato</b> ti invieremo un nuovo messaggio!
    new_application: |
        <b>ğŸ§¾ â€¢ NUOVO PROVINO!</b>

        <b>ğŸš¹ â€¢ Utente:</b> <a href="tg://user?id={userId}">{userName}</a> [<code>{userId}</code>]

        <b>â“ â€¢ RISPOSTE</b>
        <a href="{link}">Clicca per aprirle</a>
    accepted: |
        <b>ğŸ† â€¢  CONGRATULAZIONI, SEI STATO SCELTO!</b>
        <i>Â»</i> La tua candidatura ha <b>riscosso successo</b>! Siamo lieti di informarti che hai <b>superato la prova scritta</b>, a breve verrai <b>contattato dall'amministrazione</b>.
    sending_answers: |
        â³ <b>Inviando le risposte...</b>
    already_in_progress: |
        Hai giÃ  una candidatura avviata!
    already_sent: |
        Hai giÃ  eseguito una candidatura!
    work_cancelled: |
        Hai cancellato la tua candidatura.
    not_in_progress: |
        Non stai svolgendo alcuna candidatura al momento!
    answer_not_valid: |
        Mi dispiace, ma la tua risposta non Ã¨ valida. Questa domanda accetta solo risposte del tipo <b>'{type}'</b>
    invalid_length: |
        Mi dispiace, questa risposta non rispetta i criteri adeguati. La tua risposta deve contenere almeno <b>{min} caratteri</b> e massimo <b>{max} caratteri</b>. 
        Al momento, la tua risposta Ã¨ composta di <b>{length} caratteri</b>.
    only_numbers_answer: |
        <b>Questa domanda richiede solamente un numero!</b>
    work_with_no_question: |
        This type of application has no questions to answer. Please come back later.
    error_while_working: |
        There was an error while sending your answers to the admins. Please try again later.
    
    # Training messages
    train_menu: |
        <b>Welcome to the train menu!</b>

        1. Fetch Current Training Data: This option will allow you to retrieve the current training data in a JSON file format. You can use this data to examine the current state of the bot's knowledge and make any necessary changes.

        2. Train Bot: This option will start the training process for the bot, allowing it to improve its language and conversation skills based on new data.

        Please select the option you would like to proceed with.
    training_first_phase: |
        ğŸ‘‹ To commence our training process, I require three files.

        â€¢ Firstly, I need a substantial collection of diverse and legitimate words. It's preferable that the file is at least a few megabytes in size. However, please avoid selecting literature from science fiction and fantasy genres, as these often contain uncommon word formations. (ğŸ¤” For instance, the default model was trained using a Sherlock Holmes novel.) <a href="https://raw.githubusercontent.com/ImOnlyFire/applications-bot/main/gibberish/defaults/good.txt">Example</a>

        â€¢ Secondly, I need a file with around 20 simple and straightforward phrases that are easy to comprehend and free of complex language or unusual word formations. <a href="https://raw.githubusercontent.com/ImOnlyFire/applications-bot/main/gibberish/defaults/goodsm.txt">Example</a>

        â€¢ Finally, I need a file filled with overtly bad words and gibberish. This file will assist our AI model in learning what constitutes gibberish text and how to recognize it. ğŸ§ <a href="https://raw.githubusercontent.com/ImOnlyFire/applications-bot/main/gibberish/defaults/bad.txt">Example</a>
       
        <b>Let's start with the first file. Just send me the text file containing the stuff I said in the first bullet point.</b>
    training_second_phase: |
        Seems good! Now please send the second file. 
    training_final_phase: |
        Good job! now please send the last file.
    training_in_progress: |
        â³ <b>Training...</b>
    training_done: |
        ğŸ‰ Training process has been completed!
    training_cancelled: |
        Training process has been cancelled.